# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Build
    displayName: Build-Application
    jobs:
      - job: Build_App
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'app/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'


  - stage: Copy
    displayName: Copy files
    jobs:
      - job: Copy
    steps:
    - task: CopyFiles@2
      inputs:
          SourceFolder: '$(System.defaultworkingdirectory)'
          Contents: '**/*.jar*'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

  
  - stage: Artifact 
    displayName: Artifact generated
    jobs:
      - job: Artifact
    steps:

    - task: PublishBuildArtifacts@1
      inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

